- browser_utils.js
> Add support for experimental puppeteer-firefox

- browser_utils.js
- tests/selftest_waitForTestId.js
Add a new utility function to quickly look for a `data-testid` attribute.
> Add waitForTestId

- email.js
Previously multipart messages would be ignored and only `text/plain`/`text/html` in the mail itself be found.
Recurse into multipart messages to find text and html content. This is rather naive: it doesn't handle multiple parts for `text/plain` or `text/html` and prefers `multipart` parts over text/html parts on the same level.
I tried to write a test for this change, but failed due to the yolo-ness of the language.
> Respect multipart mime messages when extracting text/html content

- browser_utils.js
> Fix crash when config.exception is not defined

- render.js
- run
Also, make the header configurable for applications which desire to change it.
> Change header from integrtion test to end-to-end test

- email.js
Document `getMail`, the main function of the `email` module.
> document email

- README.md
Add some examples of how to write good and stable tests in the README.
> README: Add tips for writing good tests

- browser_utils.js
This code should run through. At a later time, it will be a warning, and then maybe some day an error.
> browser_utils: Remove debug code

- .eslintrc.json
- assert_utils.js
- package-lock.json
- package.json
- tests/test_assert_utils.js
Add assertions for `<`/`<=`/`>`/`>=` and a test for numeric.
> Add assert_utils

- net_utils.js
I forgot this during the pintf -> pentf move.
> Update default user agent

- assert_utils.js
- runner.js
- tests/selftest_assertIncludes.js
- tests/selftest_makeRandomEmail.js
- utils.js
- Make second argument of makeRandomEmail superfluous
- assert_utils: +assertIncludes
> makeRandomEmail automatic

- output.js
In general, we should silently fall back to a decent display and only show a warning if reading the file fails for whatever reason.
Don't even try to read node.js internals.
(Original crash:
```
at ClientRequest.<anonymous> (/home/phihag/e2etests/node_modules/node-fetch/lib/index.js:1455:11)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.socketErrorListener (_http_client.js:467:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:100:8)
at emitErrorCloseNT (internal/streams/destroy.js:68:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
9/27 done, 9 failed, 0 running ()(node:7378) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events.js'
```
)
> output: Do not crash if an error occurs in internal modules

- net_utils.js
- tests/selftest_fetch.js
For every request, we need to specify an agent for full control (e.g. to force Keep-Alive).
But an agent can only handle one protocol; either HTTP or HTTPS.
When following a redirect, it can happen that we switch from HTTP to HTTPS or vice versa. In these cases, recreate the agent, unless the user forced a specific one.
> fetch: Recreate agent when following a redirect from HTTP to HTTPS or HTTPS to HTTP

- email.js
This helped me understand that the current test case is idling.
> Add more verbose logs for email client

- config/prod.json
- lockserver/.dockerignore
- lockserver/Dockerfile
- lockserver/lockserver.pentf.org.nginx.conf
- lockserver/package-lock.json
- lockserver/package.json
Provide a test lockserver for everybody at https://lockserver.pentf.org/ .
> Configuraiton for lockserver.pentf.org

- runner.js
In the mystery why many runs do not terminate, the plot thickens: Apparently, the tasks are marked as done, but not reaped by the main runner.
Extend verbose logging
> runner: Add verbose task handling logs

- external_locking.js
> Fix missing config argument

- release
```bash
$ ./release
Enter new version number (current: 10.0.84):
10.0.85
```
After pressing `Enter`, the version will be changed in `package.json` and ultimately published to npm.
> Add release script

- runner.js
> runner: Set task status after screenshots and other teardown

- README.md
Changes done via our `update-readme.js` script.
> Add --debug, -d to README

- next_version.js
- release
When I have to type this manually, there's a huge change of making a mistake.
> relase: Automatically compute next version

- browser_utils.js
- config.js
- external_locking.js
- loader.js
- locking.js
- main.js
- output.js
- render.js
- results.js
- runner.js
- utils.js
This PR removes trailing whitespace. Follow-up to #176 .
> Remove traling whitespace

- README.md
- browser_utils.js
- config.js
> Expose default timeout cli flag

- config.js
- tests/selftest_no_config_folder.js
> Don't crash when no config folder is present

- main.js
- output.js
The color `gray` is unreadable in CI's.
> Replace gray cli color with dim

- package-lock.json
- package.json
Makes it easier to debug the breadcrumb tests.
> Fix ansi links not stripped in tests

- package-lock.json
- package.json
Caused by an outdated transitive dependency of nodemon (dot-prop)
> Fix security warning

- locking.js
- runner.js
- tests/selftest_no_locks.js
> Fix task without resources locking resources

- next_version.js
- src/next_version.js
Accidentally moved one file in #222 which should not have been moved. Noticed that while trying to do a release 😬
> Fix incorrectly moved next_version script

- src/loader.js
This PR fixes errors when attempting to load an ES Module test on Windows systems.
The error was caused by paths like `C:/foo/bar.mjs` which tripped up `import()`-calls. The `import()` function expects a valid URL as a parameter. This didn't throw on unix systems, because it seems like `import()` seems to work just fine with absolute paths like `/foo/bar.mjs`, even though there is not a protocol present.
The correct way is to be sure that we have a proper URL in case we encounter absolute paths. This works on all three systems. Verified that with my Mac, my Linux laptop and a Windows 10 VM.
> Windows: Fix unable to load tests in ESM

- src/loader.js
While working on #245 I noticed that it's easier to debug our test resolution when we have the actual path to the file stored somewhere. This PR adds that to our internal test case data structure. As bonus we have less places where we rely on the assumption of having a specific test directory in our code.
> Store fileName in test cases

- src/output.js
> Highlight user-space files in stack traces

- src/browser_utils.js
Found a neat way to ensure that the browser window matches the viewport size, even when the devtools are open. Got inspiration from https://github.com/codeceptjs/CodeceptJS/issues/973 .
Ran it two times with the boxine test suite and everything passes 👍 
This PR replaces #24.
> Resize browser window to viewport if headless == false

- package-lock.json
- package.json
The typings for `puppeteer` finally got updated to match the latest `puppeteer` release 🎉
> Update puppeteer + @types/puppeteer

- src/runner.js
Work around an error in `puppeteer` where taking a screenshot forcefully enables emulation, but doesn't clear it afterwards. This PR addresses that and makes sure that we restore the same viewport as before.
> Fix unable to resize viewport after screenshot

- src/browser_utils.js
- tests/selftest_assertSuccess.js
Those were previously hidden from the logged output and instead we did mark the wrapping command as the source. This was misleading and lead to confusion among the team.
Before:
```bash
Error: Unable to find text "Weiter geht" after 30000ms
53 |             assertSuccess: async () => /Juhu/.test(await getText(page, 'h3')),
54 |         });
> 55 |         await clickText(page, 'Weiter geht', {
|         ^
56 |             assertSuccess: async () => {
57 |                 throw new Error('fail');
```
After:
```bash
Error: fail
55 |         await clickText(page, 'Weiter geht', {
56 |             assertSuccess: async () => {
> 57 |                 throw new Error('fail');
|                       ^
58 |             },
59 |         });
```
Fixes #291 .
> Fix assertSuccess error not shown to user

- src/runner.js
- src/utils.js
- src/watcher.js
- tests/selftest_watch_pattern.js
> Add interactive pattern search to watch mode

- src/config.js
Watch mode is usually used during active local development. The user will have other processes running like bundlers. So let us be a good citizen and leave some CPU cores for them to take.
> Reduce CPU concurrency in watch mode

- src/browser_utils.js
This happens because puppeteer's `page.isClosed()` value is sometimes out of sync for a tiny window.
> Ignore "already closed" errors on close

- src/browser_utils.js
- tests/selftest_waitForSelector.js
> Fix waitForVisible/-Selector failing if more than 1 match found

- src/browser_utils.js
Example of a forced insecure form submission warning:
Page in the browser:
> Enrich error message when the browser displays a native error

- package-lock.json
- package.json
> Update TypeScript to 4.2.3

- src/output.js
> Add passed count to status string

- README.md
- src/browser_utils.js
- src/config.js
- tests/selftest_breadcrumb.js
> Enable breadcrumbs by default

- src/browser_utils.js
- tests/selftest_waitForSelectorGone.js
- tests/selftest_waitForTestIdGone.js
- tests/selftest_waitForXPathGone.js
> Add waitFor*Gone functions

- src/browser_utils.js
Those formatting changes sneaked into #409, again. Maybe applying them here will allow us to recover the actual changes.
> format browser utils with prettier

- src/browser_utils.js
- tests/selftest_breadcrumb.js
- tests/selftest_browser.js
- tests/selftest_clickText.js
Replaces #409, after resolving various conflicts.
> replace clickText with clickNestedText implementation

- src/internal.ts
- src/output.js
- src/results.js
- tests/selftest_flaky_result_repeat.js
First commit only formats some files with prettier, 2nd commits makes the actual changes.
Test coverage is currently limited, hijacking an existing test that didn't like the extra output line. That seems good enough for a pure output feature.
Preview:
Fixes #410
> Slow test summary

- src/browser_utils.js
This PR inserts code to wait for devtools to be fully initialized before running the initial `resizePage()` call. This resolves an issue in newer chromium versions, where the devtools take longer to initialize and we fire our resize call too early. When that happens the viewport doesn't match the specified dimensions anymore. This PR fixes that.
> Fix page resized before devtools ready with -d

- src/browser_utils.js
- src/utils.js
Increase devtools initialization window.
> Ignore execution detached error

- src/browser_utils.js
> Fix TS generating incorrect return type for getText

- Makefile
- package-lock.json
- package.json
- src/assert_utils.js
- tsconfig.doc.json
> Fix assertAlways jsdoc

- src/utils.js
> Make deprecations more obvious

- src/video-recorder.js
Safeguard against puppeteer errors in video recorder
> Safeguard against puppeteer errors

- src/browser_utils.js
- src/runner.js
This is an alternative to #437
> Avoid closing pages during teardown

- package-lock.json
- package.json
The new version fixes an issue where SIGINT could not be trapped by user code.
> Update tmp-promise dependency

- .prettierignore
- tests/esm_tests/esm.mjs
Also fix a case where an example file could be indented better.
> prettier: Ignore automatically generated files

- src/utils.js
- tests/selftest_cmp.js
Also add a test for it and its cousins.
> utils: Add cmpKeys helper function

- src/email.js
> email: Fix task name representation

- src/email.js
Allow filtering by more than just a string.
> Allow filtering emails by callable

- README.md
- src/email.js
- tests/selftest_getMail.js
When switching branches and fixing conflicts, one variable was forgotten.
Fix this, and add a self-test to ensure it never happens again.
> Fix email fetching

- tests/selftest_fetch.js
On newer node versions, this will output more information about the types, maybe even color.
> Make selftest_fetch more flexible
