output.js
Sometimes a custom filter passed via the command line won't match any test cases and I got a little confused wether something happened. I didn't make the connection in my head that the filter had a typo in it.
This PR prints an additional message in such a scenario, informing the user that no test cases were found using the supplied filter and that this is why the test count is  0.
Before:
```bash
$ ./run -e local_spa -f my_cool_filter
0 tests passed, 0 tests failed. 
```
After:
```bash
$ ./run -e local_spa -f my_test_case
No test case found with filter: my_cool_filter
0 tests passed, 0 tests failed. 
```
=> Log message when filter didn't match a test case

output.js, runner.js, tests/expectedToFail.js
This PR orders the information from importance to the user from left to right. It's best explained by comparing the output side by side.
```bash
4 running (foo bar bob  +1), 47 done, 40 more
33/104 done, 1 failed, 4 running (foo bar bob  +1)
```
Similar to the above the main information that a test has failed is moved to the beginning of the line.
```bash
test case foo FAILED at 2020-02-03T09:45:45.557+01:00:
TimeoutError: waiting for selector ".bob .bar" failed: timeout 4000ms exceeded
[StackTrace]
FAILED test case foo at 2020-02-03T09:45:45.557+01:00:
TimeoutError: waiting for selector ".bob .bar" failed: timeout 4000ms exceeded
[StackTrace]
```
=> Change status format

tests/selftest_assertEventually.js, tests/selftest_browser.js, tests/selftest_clickTestId.js, utils.js
Previously, all of these assertion methods did require a message.
Make the message optional, and part of an options object.
=> Make message optional in assertEventually and friends

output.js
The old wording was not clear about the status of these tests.
=> expectedToFail: improve wording

browser_utils.js, tests/selftest_waitForTestId.js
Centralize the testId checking and allow a dot. Move `-` to the beginning of the regular expression character group so that we can easily append future new characters.
=> Allow dot in test IDs

browser_utils.js
This was overlooked when changing the signature.
=> browser_utils: Use new assertAsyncEventually parameter format

tests/selftest_waitForTestId.js
At https://travis-ci.org/boxine/pintf/jobs/647233941 , the timeout of 102 ms (which _should_ be more than enough normally) still failed. Bump it by 10x.
=> selftest_waitForTestId: bump timeouts

browser_utils.js, tests/selftest_speedupTimeouts.js
Stolen from an ad-hoc testing framework we have and want to replace with pintf, `speedupTimeouts` can be used to run pages at faster speed, shortening JavaScript animations.
At the moment, it works with `setTimeout` and `setInterval` only (so no CSS animations or so), but that's totally sufficient for our use cases.
The function comes in two modes: In ephemeral mode (default), the speedup can be restored and is gone after the next page navigation.
In persistent mode, the speedup is applied anew upon each page navigation. This is required for traditional HTML pages which submit forms or navigate to other URLs.
=> browser_utils: add speedupTimeouts function

output.js
Quiet mode (`-q` or `--quiet`) is commonly used for parallel CI runs, where we don't want to get flooded with status messages.
But in this mode, we still want to know the final tally of all tests. Always show it.
=> Show final test summary even when --quiet is active

browser_utils.js
It turns out that in practice we often want to click labels, or `<p>` inside `<a>`.
=> browser/clickText: Match everything

main.js
In a CI context, we do not want to mark our test run as red if it all failures were expected.
=> Exit successfully if all errors were expected

browser_utils.js
Selecting _every_ element was a mistake; this would match stuff like `<meta>`, `<style>`, `<script>`, `<title>` etc. .
Instead, select only the input components plus `<div>`, `<p>`, `<span>` for people who don't like semantic HTML.
This reverts commit 38a6a84c6575069a6d4cb2d63d2d62409b5d459a.
=> browser_utils: Restrict default selection of clickable elements

browser_utils.js, tests/selftest_browser.js
The problem with a blacklist is that we are trying to match a button by text.
What happens then is that we match headers, `<p>`, and all other kind of elements which happen to share the same text as the button.
=> clickText: Switch back to a whitelist

browser_utils.js, package-lock.json, package.json, promise_utils.js, utils.js
Most frontend-based editors that leverage the TypeScript compiler under the hood use it to present the user with improved suggestions and basic type checking. These include vscode, WebStorm and Sublime (with plugins). This works because TypeScript can check JavaScript files.
_Note: TypeScript is smart enough to infer most return types, so they're not always explicitly specified._
Before:
As one can see, vscode has no clue about the type of `page`.
After:
=> Add JSDoc comments for enhanced intellisense

promise_utils.js, runner.js
Previously, one could mark the entire test as expecting to fail.
By adding
```
await expectedToFail(config, 'broken, see ISSUE-123', async () => {
defective code here..
});
```
one can now test segments as expected to fail.
=> Add an expectedToFail function

browser_utils.js, tests/selftest_waitForVisible.js
Add a `message` and timeout parameter to `waitForVisible`, along with a better error message.
Treat `visibility: hidden` as invisible.
Test that this all works.
=> Modernize & test waitForVisible

config.js
This makes sense when referring to AWS regions, e.g. `us-west-1`
=> Allow dashes in configuration name

promise_utils.js
In one instance, we forgot this argument. Assert that it's valid.
=> expectedToFail: assert that third argument was given

config.js
The PDF file with the result output is the easiest way to debug issues. Generate it by default.
=> Generate PDF file by default

.gitignore, .npmignore, package-lock.json, package.json, tsconfig.json
This PR generates TypeScript typings based on the JSDoc definitions and allows users to consume `pintf` with strict typings enabled. This will create a type definition file next to the js.
```bash
foo.js
foo.d.ts
```
An alternative to this PR would be to publish typings separate from this project on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) `@types/pintf`. Downside is that those would need to be updated manually.
=> Generate TypeScript definitions on build

output.js
In an internal run at https://gitlab.boxine.de/tonies/my-tonies/-/jobs/73667 , we saw a very strange error:
The integrationtests terminated without actually running all tasks!
If that ever happens again, output more useful information.
=> output: Self-check task status

runner.js
When a browser error occurs, the test runner should keep on going.
=> runner: Do not crash on browser error

.travis.yml, README.md, browser_utils.js, config.js, main.js, tests/fixtures/extension/content_script.js, tests/fixtures/extension/manifest.json, tests/selftest_extension.js
This PR adds a new cli flag `--extensions` to load a list of browser extensions. There is a restriction in chrome that they're only loaded in non-headless mode. The cli flag expects a list of directories which points to an unpacked browser extension.
This is useful to enhance the debugging experience, like adding `react-devtools` for easier component inspection.
=> Add support for loading browser extensions

README.md, config.js, external_locking.js, runner.js
We have one machine currently holding a lock permanently. While we should limit the locking in the first place, in the future we should be able to know where that happens.
Add the machine name in the locking ID, and add an option to output it.
Also regenerate the README.
=> Add machine name in locking info

output.js
Previously, when running 111 test cases and 11 skipped, we would display something like `99/111` done, which seems like there's some time to go, but really means that all but one test has finished.
=> output: Account for skipped test cases

.github/workflows/docs.yml, .gitignore, Makefile, README.md, browser_utils.js, package-lock.json, package.json, tsconfig.json
Generate HTML documentation and upload it to https://boxine.github.io/pintf/ .
Currently, the content of the documentation is still sparse.
Only export functions with JSDoc comments, because without `--excludeNotDocument`, [tsdoc will export _everything_](https://github.com/TypeStrong/typedoc/issues/639), including stuff like `const assert = require('assert');`.
=> Automatically generate documentation and upload it

browser_utils.js
Reason being that `--devtools` overwrites `--headless` inside the args parser of puppeteer. See: https://github.com/puppeteer/puppeteer/blob/v2.1.1/docs/api.md#puppeteerdefaultargsoptions
Error stack:
```bash
Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented
at Promise (/pintf/node_modules/puppeteer/lib/Connection.js:183:56)
at new Promise (<anonymous>)
at CDPSession.send (/pintf/node_modules/puppeteer/lib/Connection.js:182:12)
at Page.pdf (/pintf/node_modules/puppeteer/lib/Page.js:1004:39)
at Page.<anonymous> (/pintf/node_modules/puppeteer/lib/helper.js:112:23)
at html2pdf (/pintf/browser_utils.js:522:20)
at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
=> Fix crash on pdf generation when --devtools is set

version.js
When the current commit is tagged, display the tags as well.
Also clarify variable names: `..Output` is the output of a command.
In addition, use the platform's EOL instead of hardcoding `\n`.
=> Include tags in version determination

promise_utils.js, runner.js, tests/expectedToFail_section.js
With the expectedToFail section, one can mark code that is known to fail (because of existing bugs), e.g.
```
await expectedToFail(config, 'BUG-123', async() => {
throw new Error('always fails');
});
```
This is great because the failure will not be immediately displayed and the tests will remain green even.
However, sometimes the code _does_ work on some environments.
```
if (config.works) {
// known good environment
if (config.env !== 'works') throw new Error('always fails');
} else {
// known bad environment
await expectedToFail(config, 'BUG-123', async() => {
if (config.env !== 'works') throw new Error('always fails');
});
}
```
But this duplicates the whole body of the `expectedToFail` section.
Instead, we add a parameter `expectNothing`, which can be used to effectively disable the …
=> Add expectSuccess attribute to expectedToFail section

README.md, config.js, loader.js, main.js, tests/selftest_loader.js
Sometimes, despite the best naming, we just want to run all tests referencing all tests that deal with insecure HTTP, or all tests referencing BUG-123 / BUG-456.
The new option `-b`/`--filter-body` enables this, as we can use `-b http:` or `-b 'BUG-(123|456)'`.
Move the test loader into its own submodule.
Remove the TypeScript documentation, as this function is not part of the public pintf API.
Add a simple selftest for the test loader.
=> Allow filtering tests by file content

browser_utils.js, tests/selftest_attributes.js
This PR adds two new convenience functions:
- `getAttribute(page, '.my-selector', 'class')` to get any attribute of an element
- `getText(page, '.my-selector')` to get the text content of an element
=> Add attribute getters

browser_utils.js
I accidentally passed in garbage here. Fail early with a nice error message if the XPath is not even a string.
=> browser_utils: Check clickXPath argument

output.js
While the expected failures are also listed in detail below the summary line, having them included in the (unexpected) test failures is misleading. A separate counter is easier to read.
=> output: separate count for expected failures

.npmignore, README.md, browser_utils.js, config.js, config/local.json, config/localhost.json, lockserver/lockserver.js, main.js, net_utils.js, package-lock.json, package.json, pentf_example.js, promise_utils.js, render.js, run, runner.js, tests/browser_failure.js, tests/glob_tests/run, tests/maxEventListeners_tests/run, tests/selftest_clickTestId.js, tests/test_lockserver.js, update-readme.js, version.js
While this project can be used for integration test, it is much more geared towards end-to-end tests.
Rename the project to follow as such.
This also clearly distinguishes it from printf, a technical term.
Add a project statement at the top of the README about pentf.
=> Rename to pentf

Makefile
We already have all the code, but for developers dealing with many different languages and frameworks (like me) it's soothing to be able to rely on `make`.
=> Add a clean make target

.eslintignore, browser_utils.js, net_utils.js, package-lock.json, package.json, utils.js
Document `browser_utils`, `net_utils`, and most of `utils`.
Currently, named arguments do not show up – see https://github.com/TypeStrong/typedoc/issues/1274 .
Update `typedoc` and configre `.eslint` to ignore the generated doc.
=> Write documentation for the most common methods

package.json
The doc directory is 100% generated from source code, therefore not checked in, and hence should be deleted with `make clean`.
=> clean: Remove doc/

Makefile
Make our modules show up as major modules instead of externals loaded from `index.js`, and hide all private modules.
=> Improve doc generation

.gitignore, output.js, render.js, results.js, tests/selftest_resultCountString.js
Add a test dealing the somewhat obscure cases of `expectedToFail` tests _passing_ and other exotic stuff.
Share the code for the count string generation between the `output` and `render` modules.
=> Fix counts in output

browser_utils.js, tests/selftest_clickNestedText.js
~~This PR adds support for nested text nodes with `clickText`. Previously the XPath selector only took direct descended text nodes into account and would ignore nodes wrapped with a `span` or any other element.~~
~~See this comment on SO for an in-depth explanation: https://stackoverflow.com/a/55424335/755391~~
As discussed offline, I've rewritten the PR to add a new helper to match nested text nodes.
=> Add clickNestedText helper

browser_utils.js
Accidentally left in an assignment that doesn't do anything because it's overwritten just a few lines later. See: #63
=> Remove unnecessary assignment

promise_utils.js, runner.js, tests/selftest_timeoutPromise.js
Jörn noticed that the shutdown (after test results have been output) can take minutes.
Limit all shutdown tasks to 10s before outputting a warning and going on to the next task.
Add a new function `timeoutPromise` which can be used by tests as well, and test for it.
=> Add timeouts for shutdown

main.js
Jörn observed some problems with pentf-based tests hanging for a long time.
I originally posited a problem with the teardown, but another theory is that we are leaking some long-running promises in some of the tests that are _not_ torn down.
Fortunately, the workaround/fix for that is very simple: Once tests are done, exit.
In the future, we may add detection of leaked promises / timeouts, but from my cursory rasearch, that may be very complicated.
=> Call process.exit after tests are run

output.js, render.js, results.js, tests/selftest_resultCountString.js
With `--expect-nothing` or `-E`, the user can quickly disable all `expectedToFail` declarations.
This is useful to see error reports of any known bugs or missing features, especially when one of those bugs is being fixed.
However, the summary was confusing before, because it talked about _expected to fail_, although that was totally disabled above.
If `--expect-nothing`/`-E` is set, adapt the summary to show correct counts that would happen if all expectedToFail declarations wouldn't be there.
=> results: Adapt output if --expect-nothing/-E is set

output.js, package-lock.json, package.json, runner.js, tests/selftest_diff.js
This PR adds a nice diff output of the actual and expected value of assertions.
Before:
```txt
FAILED test case selftest_diff at 2020-04-29T10:16:30.785+02:00:
AssertionError [ERR_ASSERTION]: { foo: 123, bar: 23 } deepEqual { bar: 23 }
at Object.run (/Users/m.hagemeister/dev/github/pentf/tests/selftest_diff.js:5:10)
at run_task (/Users/m.hagemeister/dev/github/pentf/runner.js:22:23)
at run_one (/Users/m.hagemeister/dev/github/pentf/runner.js:111:11)
at parallel_run (/Users/m.hagemeister/dev/github/pentf/runner.js:161:29)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
After:
```txt
FAILED test case selftest_diff at 2020-04-29T10:15:21.223+02:00:
{
-  "foo": 123,
"bar": 23
}
AssertionError [ERR_ASSERTION]: { foo: 123, bar: 23 } deepEqual { bar: 23 }
at Object.run …
```
=> Add diff of expected and actual value in output

config.js, main.js, output.js, package-lock.json, package.json, run, runner.js, tests/expectedToFail.js, tests/expectedToFail_section.js, tests/selftest_diff.js
This PR adds colors to the logged output to make it a bit easier to scan for the eyes. The diff and the error stack trace have been slightly indented to better show a hierarchy.
```txt
STATUS MESSAGE
DIFF
STACK
```
Screenshots with color:
Screenshot without color via: `NODE_DISABLE_COLORS=true`:
=> Colorize cli output

output.js, tests/selftest_diff.js, tests/selftest_stringify.js
This is a follow-up to #71 .
Turns out that `JSON.stringify` doesn't sort object properties at all. This would lead the following comparison to fail:
```js
// actual
{ a: 1, b: 2 }
// vs expected
{ b: 2, a: 1 }
```
These are structurally the same objects and should not show any differences. Unfortunately for us `JSON.stringify` has no options to order object properties. I've looked at several npm packages as alternatives, but most are pretty heavy handed and come with ~20 or more dependencies. So I wrote a custom `stringify` function.
=> Fix wrong diff output by sorting object properties

utils.js
These forms are no longer used by anyone and can confuse TypeScript.
Use modern default parameters instead.
=> utils: remove legacy way of passing options

net_utils.js
Add documentation for this helper method, thereby completing documentation of `net_utils`.
=> document net_utils.setupTLSClientAuth

tests/selftest_resultCountString.js
This expectedToFail declaration was used for educational purposes and should never have been committed let alone made it into master.
=> Remove debug code

net_utils.js, package-lock.json, package.json, tests/selftest_fetch.js
For backend tests against traditional HTML & Cookie (rather than API & Token) applications, we need cookie support. One way to get that and much more is to fire up a real browser (with `browser_utils.newPage` or otherwise), but that is very resource-intensive and may break because of other stuff (e.g. CDNs).
Start a new era of enabling browser-less tests by adding cookie jar support to `net_utils.fetch`.
Also add a self-test for that.
=> Add Cookie support to net_utils.fetch

promise_utils.js
The order of promise and message was incorrectly switched in the example.
=> customErrorMessage docs: Fix example

output.js
Simplify the layout: Everything related to a failure is now indented by 2 instead of some stuff by 2 and other stuff by 3 levels deep.
Maybe in the future I'll add an option for no indent of stack traces, because that really looks best to me.
=> output: Reduce stack trace indent

main.js, output.js, run, runner.js, tests/expectedToFail.js, tests/selftest_diff.js
`options` are meta-options defined by the tested application, that determine how to arrive at the config.
But `config` is what we want, as it is an amalgamation of CLI arguments and environment config (the latter of which would be somewhat unusual for colors here).
`config` can be nested though; in particular for the pentf self-tests. It would be a very sad state of affairs if the self-tests would not run with colors.
Therefore, move color enabling to our own helper function.
=> Fix colors

.prettierignore, .prettierrc, .travis.yml, Makefile, package-lock.json, package.json
Copy over prettier settings from our similarly-managed e2etest repo.
Do not run it, and do not make it mandatory for now, as there are many PRs in flight which would be impacted.
=> Initialize prettier

.eslintrc.json, browser_utils.js, runner.js
use `eslint-disable-next-line` so that prettier does not break our eslint hints, and allow double quotes if they contain a single quote.
=> Prepare for prettier

output.js, runner.js, tests/selftest_diff.js
TIL, that `assert` will automatically add a diff output to `error.stack` if it's used in strict mode. Didn't even know that it existed in the first place! This unfortunately lead to duplicate diffs being displayed.
With this PR we'll check if there is a diff already present in the output and we'll only add our diff if it is not there.
=> Fix duplicate diff with assert.strict

main.js
When using `--no-colors`, for example to debug a problem with coloring assertions, then builtin functions like `assert.strict` should follow suit.
This does not work for nested configurations, but perfect is the enemy of good, and this seems like a sensible workaround to get the correct behavior.
=> Apply --no-colors to assert.strict

output.js, render.js, runner.js, tests/selftest_strange_exceptions.js
All normal errors/exceptions should have a stack trace, among other things.
But not all thrown values are proper errors. If we encounter such a strange non-exception exception, wrap it into our own error.
Try to get a good string representation of the value, in a feeble attempt to reproduce Python's [`repr`](https://docs.python.org/3/library/functions.html#repr).
=> Correct handling of non-Error errors

render.js, runner.js, tests/browser_failure.js
Just like `expectedToFail`, allow the `skip` function to return a string, and output that string in the results HTML/PDF.
This can be used like this:
```
skip: config => (config.env === 'prod') && 'This DoS could impact customers and is therefore not run against prod';
```
=> Allow tests to provide a reason for skipping

README.md
Skipping and `expectedToFail` are importent features that enable test-driven development among others, and thus should be documented in the README.
This documentation already includes https://github.com/boxine/pentf/pull/91 .
=> Document skipping and expectedToFail

README.md, config.js, config/localhost.js, config/localhost.json, main.js, tests/config_examples/async_javascript.js, tests/config_examples/json.json, tests/config_examples/simple_javascript.js, tests/selftest_config.js
Previously, the configuration files had to be JSON, named `config/${ENV}.json`, with `${ENV}` standing for the environment.
This is fine for most applications, but in some cases it may be desirable to use `.js` – to add comments, or event to compute the configuration (e.g. download information somewhere).
Therefore, allow JavaScript files, both ones that directly export the configuration and ones that export an async function that computes it.
Add a test for reading the configuration that doubles as examples.
While we're at it, also extend the config documentation.
In the future, we may also add YAML and TypeScript support.
=> Allow JavaScript (.js) configuration files

browser_utils.js, tests/selftest_clickSelector.js
We already have a function clickXPath to click atomically by XPath.
Add another function to click atomically by query (aka CSS) selector.
To distinguish, clarify documentation for `clickXPath` and add an example there as well.
Since the `selftest_browser` test is already quite large, add our own test.
=> browser_utils: Add clickSelector

output.js, runner.js, tests/expectedToFail.js, tests/expectedToFail_section.js
Before (colors disabled):
```txt
FAILED  test case expectedToFail at 2020-05-12T11:51:50.703+02:00:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
```
After (colors disabled:
```txt
FAILED test case expectedToFail at 2020-05-12T11:51:50.703+02:00:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
```
=> Only pad status label when colors are enabled

browser_utils.js, tests/selftest_browser.js
All our other functions take the error message as an optional named parameter `message`, but this was one of the few holdouts from the early times.
Allow both the legacy way of calling and the new one.
After a couple of releases, we will add a deprecation warning to the legacy code path, and then finally remove it.
Also add an assertion that `XPath` is a string – if the user passes in a function or `undefined`, that may end up being a valid XPath when converted to a string by accident.
=> browser_utils: Modernize assertNotXPath

config.js, output.js, render.js, results.js, runner.js
To identify flaky tests, it is very helpful to be able to re-run them multiple times.
Add a `--repeat` option that does exactly that.
=> Add --repeat option

README.md, config.js
The feature is not really experimental anymore. Also add a more helpful metavar for the `--help` output.
Regenerate the README as well.
=> Improve docs for --repeat

render.js
Just like the screenshots below, this text can cover all 3 columns.
(Before, a table cell was missing, so it looked funny with gray background.)
=> render: Make expectedToFailText cover 3 columns

tests/browser_failure.js
This test serves as a demonstration vehicle to show off pentf's result rendering.
Add `expectedToFail` and make the text easy to read.
=> Improve browser_failure test

config.js, package-lock.json, package.json, runner.js
When end-to-end tests are run in a pipeline – or, as in our main use case, in many pipelines over different projects – it is easy to miss failure.
A single missed failure doesn't (usually) hurt, but if there is a pattern of a flaky test (because of a problem with the test or the tested service, or both), then we want to know.
Sentry can already deal with errors and collate them, so add an option to use sentry.
If the `CI` environment variable is set and a sentry DSN is set, turn on sentry automatically (This enables Ops to configure the environment variable `SENTRY_DSN` and have reports show up automatically).
=> Add Sentry support

promise_utils.js
The type was plain incorrect here
=> promise_utils: Fix doc

Makefile, output.js
Simply include every *.js file, and mark all pentf-internal methods as `@hidden` to avoid documenting them as part of the public API.
=> Include assert_utils in doc

assert_utils.js, browser_utils.js, tests/selftest_assertEventually.js, tests/selftest_browser.js, tests/selftest_clickSelector.js, tests/selftest_clickTestId.js, tests/selftest_speedupTimeouts.js, utils.js
For historical reasons, the `utils` module is a grab bag of various helper functions.
Now that we have a dedicated module `assert_utils` for assert helpers, move all these assertion helpers there.
=> Move assert* from utils into assert_utils

README.md
pentf should not contribute to the global problems of [bit rot](https://en.wikipedia.org/wiki/Software_rot), so we should be _very_ conservative in deprecations.
At the same time, as long as we know all known users of the project, I feel confident in grepping their code for deprecated stuff.
=> Document deprecation policy

tests/browser_frames.js
Unfortunately, accessing frames of another origin is anything but trivial with Chrome & puppeteer. It's possible, but nothing works by default.
By simply passing in `['--disable-features=IsolateOrigins,site-per-process']` as Chrome args (`IsolateOrigins` may even be optional), everything goes back to working.
=> Add an example test for access frames

assert_utils.js, tests/selftest_lazy_assert.js
Sometimes, we want an assertion message to be very helpful, and doing so requires expensive calls (usually `JSON.stringify`, but may also other data grovelling or reading from a file).
If the assertion almos never fails, then it would be a huge waste to calculate the error message on every call.
At first, I thought this function would be too trivial to be included in pentf.
However, we already have 3 copies with differing implementations.
Add it as an official function in assert_utils.
In the future, we may add an async variant, or the ability to wrap arbitrary other assertion functions.
=> Add a lazyAssert helper function

assert_utils.js, tests/selftest_assertIncludes.js
Add a helper function to get a better message when checking for the presence a substring or an array element.
=> assert_utils: +assertIncludes

output.js, package-lock.json, package.json
While debugging a test-failure in [preact-devtools](https://github.com/preactjs/preact-devtools) I noticed that it was hard for me to quickly "scan" over the error output. I always have to concentrate to focus on the relevant information of the stack trace.
With this PR I've tried to introduce a little bit of visual hierarchy. The location of the current frame is highlighted as I've always perceived it as the most important information of the stack trace.
Verified with the output generated by [jest](https://github.com/facebook/jest) and they do the exact same thing and apply the same coloring.
To make life easier I've also marked it as a link. Not all terminals support this feature, but the GNOME Terminal specifically does. Haven't checked others. It allows users to simply click on the …
=> Make logged error stack visually more pleasing

output.js
On GitLab CI, the linkification looks totally broken:
Omit when `no_clear_line` – probably better known as `--ci` – is set.
=> output: Do not linkify on CI

main.js
Make sure to get some contrast between test name (important) and description (more of an annotation) in the list of tests output with `./run -l`.
=> main: colorize test list

output.js, runner.js
This PR adds a code-frame to directly show where the error occurred in relation to the original source code. It's optional and will only be present if the error was thrown by user code. 
Colors:
No colors:
=> Add optional code-frame to show error location

curl_command.js, net_utils.js, tests/selftest_fetch.js
Before this, cookies set during redirects did not land in the cookie jar.
Implement redirect following ourselves in order to handle the cookies.
Also, make sure we don't mutate `init` for the caller, as we are writing a lot in there.
As an added benefit, we'll see all requests in the curl output, which is much more sensible for virtually all HTTP-level tests.
=> net_utils: Support following redirects with cookies

net_utils.js, tests/selftest_fetch.js
In my attempts to optimize the function for very complicated calls, I forgot the simplest one :(
=> net_utils: Fix fetch without a third argument

README.md, browser_utils.js, tests/demo_browser_input_type.js, tests/selftest_typeSelector.js
Typing text into an `<input>` or `<textarea>` should be really simple, but sadly puppeteer's `page.type()` runs immediately, which is a recipe for flakiness.
Add a very simple alternative, a demonstration of why the alternative fails, a selftest, and document it.
=> Add a helper function to type text

render.js
The only other way to disable colors for the assert module is to disable colors globally via an environment variable. That won't work for us as we want to display colorized output in the cli.
See: https://nodejs.org/api/assert.html#assert_strict_assertion_mode
Fixes #122 .
=> Strip ansi codes from assert output.

tests/selftest_navigation_context_destroyed.js
When `clickXPath` is evaluated while a navigation context change happens, it fails as reported in #127 .
Reproduce the problematic behavior with a test.
=> + navigation_context_destroyed testcase for #127

browser_console.js, browser_utils.js, config.js, tests/selftest_console.js
This PR adds support for optionally forwarding browser console message to stdio/stderr. Values are automatically pretty printed as if they're logged from the node process itself. This is a huge advantaged compared to `karma` or other browser testing solutions. It makes debugging tree-like structures a lot easier (we have lots of those in Preact :stuck_out_tongue: ).
Due to limitations in puppeteer and the devtools protocol we need our own serialization format (essentially JSON) and pass it around as a string.
Supported data types:
- Primitives (string, number, boolean, null, undefined)
- Arrays + Objects
- Error objects
- Functions, Arrow Functions and classes
- Circular Data
- Map + Set
Screenshot:
=> Add support for forwarding browser console messages

email.js, tests/selftest_email_socket_timeout.js
Default to a compatible 5 minutes, which should be fine for most applications.
=> email: Make socket timeout configurable

config.js, tests/selftest_concurrency.js
Allow setting concurrency by number of CPUs
The concurrency setting must unify to competing interests:
The lower it is, the more stable tests tend to be. The higher it is, the faster tests run.
Optimal would be to use 100% CPU all the time, with no thread ever waiting.
In practice, we must make a trade-off, because we don't know how CPU-intensive the loads are.
Do so automatically by defaulting to 4 + Number of CPUs. For a small CI system with one or two CPUs, this will reduce the load in half.
For very beefy systems, it will make them use more CPUs.
For most current desktop/laptop users, the concurrency remains about the same.
In practice, on many CI-style systems we see more CPUs than we can actually use, so we may need to add a further limit instead of just `cpus`.
[I asked in the …
=> Change default concurrency to vary based on CPU count

output.js, results.js
This is an attempt to make the summary output easier to read. It's a bit longer than the current output though. Let me know what you think :+1: 
Before:
After:
=> Change summary layout

browser_utils.js, tests/selftest_intercept.js
Puppeteer only allows a single `request` handler, which can lead to awkward scenarios where requests should be intercepted at different point in times.
```js
page.on('request', request => ...);
// Second call throws
page.on('request', request => ...);
```
This PR resolves that by adding support for multiple abstraction handlers via a tiny abstraction. 
```js
const { interceptRequest } = require('pentf/browser-utils');
await interceptRequest(page, request => ...);
// Add as many as you want, will be resolved
// in the order they were registered with.
await interceptRequest(page, request => ...);
await interceptRequest(page, request => ...);
...
```
=> Add support for multiple interception handlers

output.js
This PR makes some minor changes to the console runner output.
- Fix missing newline after error message e9f39bf
- Only show code frame for user code 5f3c316 
- Only show failed summary if there are failed tests 26ef3b1
- Only show success summary when tests succeeded c78d1b8
-  Fix code frame line numbers being off by 1 92d7df5
=> Update error cli output

external_locking.js
In CI, runners tend to have very non-descriptive names such as `runner-4dd9cc6e-project-42-concurrent-0-root-1595488326463`.
Instead, include project name, branch/tag name etc., to quickly identify the pipeline.
=> external_locking: Set more descriptive locking name when running in CI

main.js, render.js, runner.js
In our CI, we're seeing pentf runs hang after finishing all tests.
Log more information if `-v` is given.
=> runner: Verbose log status on end

lockserver/lockserver.js
We want to allow longer and thus more descriptive client names, including pentf version, branch names, etc.
This is already implemented in our proprietary lockserver.
=> lockserver: Allow a client length of up to 256 chars

output.js
Normally, whenever we output something, we want the current status at the bottom.
`--status-interval` has a different approach: It just prints the current status at regular intervals.
Outputting the current status again is redundant in these cases.
Therefore, circumvent normal status output and just output our line.
=> output: Make --status-interval circumvent normal printing rules

runner.js
We are still seeing some cases where pentf never terminates.
Somehow, tasks switch from running to non-running without any logs being generated.
I've reviewed the most likely culprits (runner and output) and found no explanations.
To aid debugging if this happens again, make logging much more verbose in the runner, and output the currently running tasks.
We will likely revert this after the bug has been found, but let's see how verbose the output feels in practice.
=> runner: very verbose logging

external_locking.js, tests/selftest_ci_client_name.js
The new limit for clients is 256, allowing us to stuff a bit more in there:
- Fix general display (prefixDash previously _appended_ a dash)
- Apply limits to all CI variables
- Make sure to properly trim spaces and newlines (wtf?) in CI environment variables
- Include a URL to the CI job if available!
- Include pentf version to spot out-of-date jobs (or exclude older pentf versions from error analysis)
=> external_locking: Improve & fix client name under CI

runner.js
This makes it easy to see which project is affected, and one can jump to the pipeline directly.
=> runner: Set job URL in sentry reports

version.js
Version determination (e.g. in PDFs) works by looking at the git state. However, in docker images, there often is no `.git` directory.
Instead, look at the environment variables during building. The docker image can then be built as:
```
docker build \
--build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" \
--build-arg "CI_COMMIT_TAG=$CI_COMMIT_TAG" \
--buil-arg "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH" \
--tag $CI_REGISTRY_IMAGE:latest .
```
=> version: Fall back to CI environment variables

external_locking.js, locking.js, runner.js
This PR makes the separation between `config` and `state` more clear by keeping them separate.
=> Remove config reference from runner state

browser_utils.js, promise_utils.js
In practice, `browser_utils.closePage` sometimes doesn't terminate! Abort if one of these calls takes too long.
=> browser_utils: Add timeouts for closePage

output.js, results.js
This PR moves all result logic into `getResults`. Previously there were some functions where that logic was duplicated for a status log.
=> Centralise result handling

runner.js
In https://gitlab.boxine.de/toniecloud/e2etests/-/jobs/114760, task #27 never finished taking screenshots.
Add a timeout. Adapt the error message to show the task number as well (e.g. `#42`), because that's what we output at other places, on account of being shorter.
=> runner: Add a timeout for screenshot taking

browser_utils.js, tests/selftest_language.js
Fixes the following error when `setLanguage()` is called multiple times in a test:
```
Uncaught TypeError: Cannot redefine property: language
at Function.defineProperty (<anonymous>)
at <anonymous>:2:16
at <anonymous>:16:7
```
=> Fix unable to overwrite language multiple times

config.js, main.js, tests/selftest_args_debug.js
I've asked around how devs debug single tests and practically everyone is using `-k --devtools`. They were not aware of `--forward-console`. Seeing that the combination is that common, it leads me to believe that there is value to unify them behind a single flag for debugging single test cases.
=> Add --debug preset flag

release
- Automatically call `./update-readme.js` to avoid the busywork of calling it manually.
- Add a 5s timeout before releasing.
- Only activate `-e` when the commads get interesting.
=> Extend release script

.editorconfig
This helps editors initialize new files with the correct indentation, encoding, etc. It is a universal standard that's supported by all mainstream editors (including vim + emacs). See https://editorconfig.org/
=> Add editorconfig for IDEs/Editors

config.js, render.js, tests/selftest_result_order.js
This PR orders results in generated artifacts by severity, meaning failures are listed first. This affects only the artifacts themselves, not the status output in the cli which is very different.
=> Order results by severity in generated artifacts

runner.js, tests/selftest_teardown.js
This PR adds support for effectful teardown functions that can be used for cleanup code. A use case for that is deleting a user in a database, releasing resources etc. It's generic enough that it can be used for anything. Teardown hooks will be invoked after a task is completed, regardless of the failure state.
```js
async function createUser(config) {
const user = await apiFetchUser();
onTeardown(config, () => apiRemoveUser(user));
}
async function run(config) {
const user = await createUser(config);
// ...do some test assertions with the user
// User will be deleted automatically at the end of the test
}
```
Fixes #121 .
=> Add support for effectful teardown functions

runner.js
Before:
```bash
[7m[34m STATUS [39m[27m at 2020-07-29T09:27:38.647Z: [33m82/83 done[39m, 1 running
my-test [31m10min 5s[39m
```
After:
```bash
STATUS  at 2020-07-29T09:27:38.647Z: 82/83 done, 1 running
my-test 10min 5s
```
=> Strip ansi color codes from Sentry breadcrumbs

runner.js
Waiting 30s for a screenshot is a bit much. Reduce that timeout to 10s.
=> Reduce screenshot timeout 30s -> 10s

email.js
Makes it easier to see which task a message is corresponding to.
=> Print task name in email logs

output.js
Not sure what happened, but the logic was backwards with `PENTF_SHOW_CODE_FRAMES`. This PR corrects that.
=> Fix missing code frame on unset env variable

browser_console.js, browser_utils.js, tests/selftest_newtab.js
This PR fixes the following error:
```bash
Cannot read property 'default_timeout' of undefined
```
Problem is that when a frame or a page is created via standard functions from `puppeteer`, they won't have our internal properties. Therefore we need to lift them up to the nearest common ancestor. The nearest one is the `Browser` instance and with that both frames and pages work.
=> Fix error on tryping to read default timeout

config.js, locking.js, main.js, output.js, tests/log_file_tests/foo.js, tests/log_file_tests/run, tests/selftest_log_file.js
This PR adds a new command line flag `--log file FILE` to persist log messages to disk. It will always print all messages, regardless if `--verbose` or `--locking-verbose` was set or not.
=> Write logs to disk via --log-file

browser_console.js, browser_utils.js, tests/console_navigation/console_test.js, tests/console_navigation/run, tests/selftest_console_navigation.js
During tests navigation may happen quickly and the execution context may already be destroyed before we attempt to serialize the messages. In this case we can just fall back to leverage the string based format from puppeteer.
=> Show fallback value if console message cannot be serialized

config.js, main.js, tests/selftest_glob.js
This PR adds support for `--tests-glob` which was previously only limited to an option that could be passed to `pentf.main(...)`.
=> Add --tests-glob argument

tests/selftest_console_navigation.js
This test fails from time to time on our CI: https://github.com/boxine/pentf/pull/203/checks?check_run_id=939744043
=> Skip timing sensitive test

browser_utils.js, config.js, output.js, runner.js, tests/selftest_breadcrumb.js
Test cases which error due to running longer than the allowed time limit are hard to debug as we have no clue where it hanged. With this PR we always save the last successful operation and print that when we run over the timeout limit.
Note that this only works for our own operations. There is no way to hook into the native ones from `puppeteer` as far as I can tell.
Example:
=> Print last successful fn call on timeout error

browser_utils.js, runner.js, tests/selftest_breadcrumb.js
This PR collects more detailed breadcrumbs if that feature is enabled. The distinction between exit and enter functions should make it more clear what the last breadcrumb represents. On top of that we wrap common puppeteer `Page` functions in case an error happens somewhere inside `puppeteer` itself.
=> Add enter/exit breadcrumbs

browser_utils.js, tests/selftest_assertNotTestId.js, tests/selftest_breadcrumb.js
This PR adds a new `assertNotTestId` function, which checks for the abscence of a Test ID.
=> Add assertNotTestId function

browser_utils.js, tests/selftest_assertNotSelector.js, tests/selftest_breadcrumb.js
This PR adds a new `assertNotSelector` function, which checks for the abscence of a selector.
=> Add assertNotSelector function

output.js
We always replace any leading tab character with 2 spaces. The `normalized` version will be longer than the raw `line` if there were tabs. The variables were in the wrong order.
=> Fix wrong column offset with tab indentation

src/browser_utils.js, tests/selftest_browser_close.js
This PR removes the need to have to call `closePage()`  explicitly at the end of each test where a browser was opened. Whenever a page is opened, it will be scheduled to be closed on teardown automatically if it is still open.
One can still close browsers via `closePage()` manually in tests like usual.
=> Close browser pages automatically on teardown

src/loader.js, tests/selftest_suite_skip.js
This PR fixes an issue where skipped tests of a suite would not show up in any runner logs or the summary at the end. The issue was caused by the suite loader simply ignoring skipped tests, instead of marking them as skipped and push them into the runner queue.
=> Fix skipped suite tests not visible in summary

babel-transform-commonjs-to-esm.js, src/version.js, tests/selftest_version_pentf.js, tests/version_pentf/run
- It was pointing at the wrong target.
- `__dirname` is not available in ESM enviornments, use babel to add a polyfill
=> Fix pentf-version throwing in esm

src/config.js, src/output.js, src/render.js, src/runner.js, tests/selftest_flaky_detection.js
This PR adds a new command line flag to re-run failing tests the specified amount of time. If the test passes before reaching that limit it is marked as `flaky`. This should ensure that our tests remain green, even if there are hickups on the backend side. Note that the stack traces of flaky tests will still be logged and printed in the results report.
The running status output needs to be improved, because it's based on tasks instead of tests and therefore will never print tests as being flaky. In my opinion this is better left for another PR. Happy to do it here to, if requested.
=> Add flaky test detection

src/output.js
Node's `assert` module appends the diff output not just to the error message, but also prepends it to the stack property. This PR corrects that, so that we don't show duplicate diff messages.
=> Fix duplicate assert diff output

src/output.js, src/render.js, src/results.js, src/runner.js, tests/flaky_tests/error.js, tests/flaky_tests/flaky.js, tests/flaky_tests/run, tests/flaky_tests/success.js, tests/selftest_flaky_detection.js, tests/selftest_flaky_result.js
With flakyness detection in place we're now in the situation where a `task` result doesn't map 1:1 to a test result anymore. Instead X tasks are grouped together to determine if we have a flaky test or not. For a setting of `--repeat-flaky` the result should be reported as:
```txt
1 flaky (foo)
```
instead of:
```txt
2 failed (foo, foo[1])
1 success (foo[2])
```
To do that the status reporting is based on tests results instead of tasks. Most of the building blocks were already in place for PDF and markdown generation, but the `runner` did it's own status calculations. This PR reworks it, so that the runner builds up test results incrementally.
So the runner status is composed of the following numbers:
```txt
10/100 done, 1 failed, 1 expected to fail, 3 flaky
^     ^          ^           ^ …
```
=> Refactor result + status to be based on tests

src/output.js, src/render.js, src/runner.js, tests/flaky_tests/flaky.js, tests/selftest_flaky_result_repeat.js
This PR ensures that `--repeat` works together with `--repeat-flaky`. We initially grouped tests by `task.id` but that doesn't because `task.id` is meant to be unique. Instead we group on `task.name` which is much more reliable and makes the `--repeat` case work without much work. Each repeated test is treated as a unique test case internally, so we can correctly group related flaky detection runs.
=> Fix flakyness detection not working with --repeat

src/render.js, src/runner.js, tests/screenshot_tests/error.js, tests/screenshot_tests/run, tests/selftest_result.js
This PR fixes an error where screenshots weren't included in the result files. They were all present in the screenshots directory, but #231 had a regression where the screenshot path was not included in the result objects.
=> Fix screenshots missing in results

src/browser_utils.js, tests/selftest_navigation_context_destroyed.js
Whenever a navigation occurs and we're waiting for an element, `puppeteer` will throw an `"Execution context was destroyed error"`. The official docs suggest manually waiting on navigation events:
```js
await Promise.all([
await page.waitForNavigation(),
await waitForSelector('foo')
]);
```
This is annoying to write and has lead to flaky tests for us. Based on that a better solution is to catch these errors internally and simply retry our matcher functions. The above snippet becomes a lot shorter with these changes:
```js
await waitForSelector('foo');
```
Fixes #127 .
=> Guard against "Execution Context destroyed" error

src/config.js, src/loader.js, tests/parse_args.js, tests/selftest_loader.js
This PR allows any config property to be passed to `pentf.main()`, not just a few limited ones like before. Any actively passed cli flags will take precedence over properties passed via `pentf.main()`.
=> Support full config object in pentf.main

src/loader.js
Turns out that the regex to allow non-js files to be passed through to `require` for `ts-node` and other compilers was a bit too greedy. Normal module paths like `importFile('puppeteer')` **must not** be passed to `require` when one of the parent files is in ESM mode.
Note that we cannot use that `path.isAbsolute` method to check if we're dealing with a relative path, as we get a mix of urls and paths in ESM. We can pretty certain that a module path/url has no dot in it, so we should be fine.
=> Fix broken module loading in esm mode

src/assert_utils.js
When an error occurs during `assertAlways`, we always want to throw.
=> assert_utils.assertAlways: Fix parameter documentation

src/main.js, src/render.js, src/runner.js
We encountered a few runs where no PDF file was generated. Add more log statements to see where pentf aborts.
=> Add more verbose logs

src/main.js, tests/selftest_log_file.js
Turns out that the log file was always written to the directory from where the process was launched, not where the sh script actually resides.
=> Fix incorrect log file location

src/config.js, tests/config_file/pentf.config.js, tests/config_file/pentf.foo.config.js, tests/selftest_config_file.js
Most JavaScript tools support `[toolname].config.js` as a config file. These include, but are not limited to `babel.config.js`, `jest.config.js` and many others. The it's implemented is that it's loaded before the environment specific files, so that those can overwrite what's in `pentf.config.js`.
Based on #254 . Marking as a draft until that PR is merged.
=> Add support for --config FILE flag

src/net_utils.js, src/utils.js
Node has a native promisified version of the `fs` module, so there is no need to create our own version.
=> Switch to always use native fs-Promise API

bin/cli.js, run, src/config.js, src/loader.js, src/main.js, src/output.js, src/version.js, src/watcher.js, tests/console_navigation/run, tests/error_output/run, tests/esm_tests/run, tests/flaky_tests/run, tests/glob_tests/run, tests/log_file_tests/run, tests/maxEventListeners_tests/run, tests/no_clear_line/run, tests/screenshot_tests/run, tests/selftest_loader.js, tests/selftest_no_config_folder.js, tests/selftest_version.js, tests/skip_tests/run, tests/suite/run, tests/timeout_tests/run, tests/ts_node/run, tests/version_pentf/run, tests/watch_tests/run
It's replaced by globs which are for more flexible when the tests files are not in a single folder
=> Remove config._testsDir

Makefile
With the move in ad0819cb32d6967b8f52cf9e8a85c4cbaff8626a, we also must update the Makefile
=> Makefile: Fix doc dependencies

tests/selftest_watch_slow.js
Noticed that I forgot to close the watcher child process in a test case. All the other watch tests are correct.
=> Add missing teardown function

src/assert_utils.js, tests/selftest_assertHttpStatus.js
This function can be used to elegantly check the result of calling `fetch`, and get a nice error message.
=> + assertHttpStatus helper function

src/output.js, src/runner.js, tests/selftest_console_self.js
Before:
```bash
0/1 done, 1 running (selftest_console_self)foo
foo
1 tests passed
```
After:
```bash
foo
foo
1 tests passed
```
=> Fix console.logs messing up status line

src/main.js
This is a function, and thus cannot be read from config, but needs to come from `options`.
=> Fix defaultConfig

src/main.js
Since we now require `fs.promises`, we can simply use `fs.promises.readFile`. Consequently, our `readFile` was deleted in 55979686040b2a9eeedc24fb46f5659c07f056b8, but we need to remove all references to it.
=> Remove references to pentf.utils.readFile

src/assert_utils.js, tests/selftest_assertNotIncludes.js
Add a helper function to assert that a string is _not_ contained in another.
=> + assertNotIncludes

.github/workflows/test.yml, assert_utils.js, browser_console.js, browser_utils.js, config.js, curl_command.js, email.js, external_locking.js, loader.js, locking.js, main.js, net_utils.js, output.js, package.json, promise_utils.js, render.js, results.js, runner.js, tests/selftest_browser_close.js, utils.js, version.js
Main reason: Node <=12 doesn't support async stack traces. Since we make heavy use of `async/await` every stack trace will only be one entry long. The current LTS is Node 12, but in just three weeks it will be replaced by Node 14.
=> Remove support for Node 10

src/browser_utils.js, tests/selftest_clickNestedText.js, tests/selftest_clickSelector.js, tests/selftest_clickTestId.js, tests/selftest_clickText.js, tests/selftest_clickXPath.js
Many frontend frameworks create DOM nodes before attaching event listeners. In those cases we may trigger the click event too early and run into a race condition.
We cannot automatically retry a click, because it can have side effects. Therefore only the user knows under which conditions the check should be retried.
The cypress folks have a fantastic blog post about this problem: https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/
=> Add optional success assertion for click functions

src/config.js, src/loader.js
This PR fixes files not being reloaded in watch mode. The heart of the issue is that we only have access to the module cache when we are not in `type: "module"` mode. With native ES-Modules we have [no way to unload a module](https://github.com/nodejs/modules/issues/307) as that's not part of the spec. It defines module loading as being idempotent.
In the long term it looks like we need to switch to workers to be able to unload files. That's something for later though as it requires a bit more thought.
_Note: Had to shuffle the `findPackageJson` function around to avoid a circular import._
=> Fix watch mode not reloading changed files

src/loader.js, tests/selftest_esm.js
The check if we should use import was wrong. With support for Node 10 dropped, we can simplify it a lot and avoid potential gotchas.
The regression was introduced in #273 yesterday.
=> Fix esm loading regression

babel-transform-commonjs-to-esm.js, src/loader.js
Missed an edge case where a `commonjs` project may load a `.mjs` file and we therefore switches to `esm`. We **must not** fall back to `commonjs` and always use `import()` from then on.
=> Force esm to always use dynamic import

src/browser_utils.js, src/config.js, src/loader.js, tests/selftest_config.js, tests/selftest_loader.js, tests/selftest_no_config_folder.js
This prevents an error where importFile() tried to find the module type when importing a node-specifier like "puppeteer". In those case we don' have a folder to start the lookup and we'd silently fail. We already _have_ a reference to the package.json during initial config loading, so we can load that information there and just pass it as an argument to `importFile()`.
=> Load module type upfront

src/main.js
When `--list-locks` or so is given, the runner returns `undefined`, and that is correct, because no tests were run.
Correct handling of this.
Fixes #281
=> Do not try to parse test results if runner terminated because of CLI option

src/config.js, src/render.js, src/runner.js
Include the CPU count in the rendered PDF. This can help to diagnose running on the wrong runner in a CI environment.
=> Report CPU Count

src/config.js
The `module` field is not used by node and more or less a sort-of proprietary field for bundlers.
=> Fix esm package.json detection check

src/watcher.js, tests/selftest_watch_enter.js
Like the title says: This PR allows the user to press enter during watch mode to re-run the tests with the current filter set.
This addresses one point mentioned in #284
=> Re-run tests on pressing enter in watch mode

src/browser_utils.js
People were confused about the `assertSuccess` name and proposed `retryUntil` as a more fitting alternative. This PR keeps both variants working, but marks `assertSuccess` as deprecated
=> Promote retryUntil as an alias to assertSuccess

src/watcher.js, tests/selftest_watch_pattern.js
This PR adds support for toggling debug mode by pressing `d` during watch mode.
=> Add support for toggling debug mode during watch

src/main.js, src/runner.js
One of the strong points of `pentf` is that browser windows are kept open on test failure if `--keep-open` or `--debug` is set. This is extremely useful for debugging. During watch mode we will more have one run and it becomes annoying to manually close old browser windows. This PR changes that so that we will close any remaining browser windows before starting the next run.
=> Watch: Fix previous browser windows kept open on next run

package-lock.json, package.json, src/browser_utils.js, src/output.js, src/render.js, src/runner.js, tests/selftest_accessibility.js
This PR integrates `axe-core` for doing accessibility tests into pentf. Users can assert how accessible a page or frame is by calling `assertAccessibility(config, page)`. If there are any resulting violations they will be shown up in stdout as well as in the generated PDF file. Each violation contains a short description and a link to a detailed one.
FYI: There is an actual screenshot instead of a black rectangle.
CLI-Output:
PDF-Output:
=> Add support for asserting accessibility violations

src/runner.js, tests/selftest_teardown_task_error.js, tests/teardown_task_error/run, tests/teardown_task_error/teardown.js
This PR exposes the `Error` object of a failed task in `task_config` so that any teardown hooks can decide to apply a different teardown based on if a task failed.
=> Expose task error for teardown functions

src/browser_utils.js, src/runner.js, tests/screenshot_popup_tests/error.js, tests/screenshot_popup_tests/run, tests/selftest_popup_screenshot.js
If a popup was opened via `window.open()` we would not include a screenshot of that frame in our reporters. Popup windows are actual pages themselves internally in `puppeteer`, so we can safely store them along with our "normal" pages.
The PayPal integration is probably one of the most popular users of the `window.open()`-API. With this PR we'll include a screenshot of the PayPal popup window content in our error output.
=> Include screenshots of open popup windows

src/browser_utils.js, tests/selftest_assertSuccess.js
Previously we always aborted if we couldn't find the original selector. This causes problems when the page navigates and the original selector is not present anymore after the click.
=> Fix retryUntil failing when original selector is not present

src/email.js, src/utils.js, tests/selftest_makeRandomEmail.js
When we repeat tests we usually append a suffix to the test name like `[2]`. The generated email address will be based on that and appends a hash to it. Turns out that having `[` or `]` in the address isn't really supported, except im some edge cases. See this thread on SO: https://stackoverflow.com/a/2049510
This was the reason emails didn't come through and I can confirm that they reach their destination with this fix in place in our `dev` environment.
=> Fix invalid characters in generated email addresses

package.json, patch-types.js, src/browser_utils.js, src/promise_utils.js
TypeScript doesn't support package export maps yet. Therefore it doesn't know about entries, other then the one listed in "types". Using explicit declare module declarations works around that limitation. As a plus we don't need to copy all the `.d.ts` files over to the project root folder 👍
=> Types: Fix no intellisense for package entries

src/browser_utils.js, tests/selftest_browser.js, tests/selftest_clickNestedText.js, tests/selftest_clickTestId.js, tests/selftest_clickText.js, tests/selftest_clickXPath.js, tests/selftest_click_layer.js
This PR addresses an error where it was possible to click on visible elements, despite them being hidden behind another. Calling `.click()` directly on the DOM node doesn't check for that, but puppeteer's `Mouse` module does.
In the following example taken out of the test in this PR we can see that a red box is positioned directly above the button we intend to click. A real user won't be able to click this button because the box captures the click event. Before this PR pentf allowed that, even though `visible: true` was set.
=> Fix able to click on hidden elements

src/browser_utils.js, tests/selftest_click_layer.js, tests/selftest_click_layer_iframe.js
Account for scrollable containers if we want to click on a visible element. Most of the code deals with special handling of `iframes` whose position inside the parent frame needs to be included in the final mouse coordinate calculations.
This PR is a follow up to #335.
=> Ensure element is scrolled into view before clicking it

README.md, src/browser_utils.js, src/config.js, tests/selftest_interactions.js, tests/selftest_interactions_iframe.js
One frequent issue with e2e testing SPAs is that we can't sometimes be sure if an element was clicked. Because there is no visual hint, users would often assume that their selector is wrong, even though it 
was correct.
This PR shows visually which element was clicked to solve that. It can be enabled via the `--show-interactions` command line flag that's automatically enabled when passing `--debug`.
=> Visualize user interactions on the page (clicks)

.gitignore, package-lock.json, package.json, src/browser_utils.js, src/config.js, src/internal.ts, src/runner.js, tests/selftest_snapshot.js, tests/selftest_snapshot_update.js, tests/selftest_snapshot_viewport.js
This PR adds an `assertSnapshot` function that can be used to compare previous screenshots to current ones. When there is a difference between the two it will mark differences visually like below. Existing snapshots are always updated if there is no expected one found or if `-u, --update-snapshots` is passed via the CLI. By default snapshots are stored in `./snapshots` as I assumed that the reference images should be committed into git.
Replaces PR #28 .
Actual:
Expected:
Diff:
=> Add support for comparing screenshots

src/internal.ts, src/runner.js
This allows user functions to validate if a resource was locked by the runner before attempting to use it in the test.
Something like:
```js
function resetTonie(config, tonieId) {
if (!config.resources.some(r => r === tonieId)) {
throw new Error(`Forgot to specify Tonie id ${tonieId} in test resources');
}
// ...
}
```
=> Pass through task resources for custom validation

src/browser_utils.js
This prevents unnecessary errors when the user closed a page themselves:
```
Error: Protocol error (Runtime.evaluate): Session closed closed 
```
=> Fix wrong config variable name in closePage

src/browser_utils.js, src/runner.js, tests/selftest_user_data_dir.js
For some tests we need to verify that values in `LocalStorage` persist across browser sessions. To test that we need a shared user profile, because `puppeteer.launch()` creates a unique one on each call.
=> Add createUserPrrofileDir to create temporary user profiles

src/config.js
On several users the default setting was too high leading to lots of test timeouts caused by scarce CPU resources.
~The new default is number of CPU cores minus one for the main thread. This is the same value used in [jest](https://github.com/facebook/jest/blob/196e5731c8985dbdb6ce7d224c9dd4348f356009/packages/jest-config/src/getMaxWorkers.ts#L25)~
=> Lower default concurrency to the amount of CPU cores

src/browser_utils.js, tests/selftest_waitForSelector.js
Users where confused why the naming of our functions wasn't consistent:
- `clickTestId` -> `waitForTestId`
- `clickXPath` -> `waitForXPath`
- `clickText` -> `waitForText`
- `clickSelector` -> `waitForVisible`?
This change makes the latter consistent by adding `waitForSelector`. Internally `waitForVisible` becomes an alias of `waitForSelector` which always passes `visible: true` around.
Fixes #346 .
=> Add waitForSelector for consistency

src/browser_utils.js, tests/selftest_resizePage.js
This allows users to resize the window so that the page matches the specified dimensions. Contrary to `page.setViewport()` this doesn't rely on emulation mode in non-headless environments and thereby allows the user to resize the page by dragging the window corners.
Fixes #347 .
=> Extract page resizing into re-usable function resizePage()

README.md
the .test sub-extension is redundant and not mentioned in the example below. And the example below uses a tests folder, so keep the naming consistent here.
=> README: improve tests-glob example

README.md
This should run everywhere and doesn't need any configuration. The more complex example can still tease other capabilities besides browser-based testing.
=> readme: add browser based example

src/browser_utils.js, tests/selftest_interactions_trusted.js
So far those errors only pop up when trying to inject stuff into the native browser warning pages that warn for insecure form submission. In that case skip injecting the interaction UI. This PR prevents noisy console errors like this:
=> Don't inject interaction ui in trusted types context

package-lock.json, package.json, src/browser_utils.js
For some reason Puppeteer completely ignores the environment variable
on arm64 systems
=> Workaround broken executable path on M1 macbooks

package-lock.json, package.json, patch-types.js
Newer TypeScript versions have trouble resolving package entries via an ambient declaration file. They seem to always traverse the directory directly instead and disregard what's defined in package.json, except for the main entry.
The only solution that works is to store types in the root folder again.
See: https://github.com/microsoft/TypeScript/issues/33079
=> Fix types for package exports not found.

src/assert_utils.js, tests/selftest_waitFor.js
Saw that devs struggle with the purpose of assertEventually. We noticed that it's commonly used for 2 use cases and it's better to split them up.
=> Add waitFor and waitForPass as shorthand for assertEventually

src/locking.js, src/output.js, src/results.js, src/runner.js
- Don't swallow errors thrown by the locking server
- Print waiting for locks message when running < concurrency
- Fix `0 running ()` -> `0 running`
Fixes #387, #388
=> Improve locking awareness

src/assert_utils.js, src/browser_utils.js, src/output.js, src/promise_utils.js
It's much easier for mere mortals read `12s 50ms` compared to `12050ms`
=> Print timeouts in human readable time instead of ms only

src/runner.js
Sometimes, the test teardown fails. In these cases, show the full stack to aid debugging.
Previously:
```
INTERNAL ERROR: failed to run teardown for #toniebox_claim_tonie (toniebox_claim_tonie): TypeError: encodeURIComponent(...) is not a function
```
With this PR:
```
INTERNAL ERROR: failed to run teardown for #toniebox_claim_tonie (toniebox_claim_tonie): TypeError: encodeURIComponent(...) is not a function
at _headless_sso_login (/home/phihag/e2etests/lib/sso_utils.js:550:9)
at sso_api_delete_account (/home/phihag/e2etests/lib/sso_utils.js:594:33)
at auth_headless_delete_account (/home/phihag/e2etests/lib/auth_utils.js:78:12)
at /home/phihag/e2etests/lib/auth_utils.js:96:42
at /home/phihag/e2etests/node_modules/pentf/src/runner.js:198:91
at Array.map (<anonymous>)
at run_task …
```
=> runner: Show full stack if teardown crashes

src/internal.ts, src/output.js, src/render.js, src/runner.js, tests/breadcrumb/no-page.js, tests/breadcrumb/run, tests/breadcrumb/with-page.js, tests/selftest_error-page-urls.js
Next to the error stack trace we print all opened urls. This makes it easier to understand at which point a test failed when elements are not found.
Fixes #405 , #404, #384 .
=> Print urls of open pages on test failure

babel-transform-commonjs-to-esm.js, tests/test_esm_transpile.js
This PR adds support for transpiling the following pattern for our ESM build of pentf:
```js
function bar() {}
module.exports = {
foo: bar
}
```
=> ESM: Add support for transpiling named re-exports

package-lock.json, package.json
**Fix dependencies to allow `npm install` on ARM64 based Macs**.
Reference:
- https://sharp.pixelplumbing.com/install#apple-m1
- https://github.com/puppeteer/puppeteer/pull/7099
=> Fix m1 mac dependency installation

src/runner.js, tests/selftest_teardown_sequence.js
To avoid the page being closed prematurely by one of the teadown hooks,
we need to run them in sequence.
=> Fix page being closed in middle of teardown hooks

.github/workflows/test.yml, .gitignore, src/browser_utils.js, src/config.js, src/internal.ts, src/runner.js, src/video-recorder.js, tests/selftest_video.js, tests/video/run, tests/video/video-fail.js, tests/video/video-success.js
This PR attempts to add video recording capabilities to `pentf`. It leverages the experimental devtools [Screencast API](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast), which despite its experimental state seems to work flawlessly.
Todos:
- [ ] Properly detect `ffmpeg` on the system across different OSes
=> Add browser screen recorder

src/browser_utils.js
If taking a screenshot fails, avoid swallowing all errors.
First try again to take the screenshot without the selector. Not super useful, but better than nothing.
Also drop the `return null` - if taking the screenshot without the selector also fails, let the whole thing fail, so we can fix it properly.
=> assertAccessibility: improve screenshot error handling

src/browser_console.js
The browser's console API allows messages to be grouped via `console.group()` and `console.groupEnd()`. These two methods don't exist in node and would therefore lead to a crash when attempting to call them.
=> Fix console.group crashing when forwarding logs

src/curl_command.js, src/net_utils.js, tests/selftest_curl_command.js
Make sure `-c` works when the body is a `URLSearchParams` instance.
While we're at it, also fix some related cookie handling, make sure we await setting the cookies.
=> curl_command: Fix & test handling of URLSearchParams

.github/workflows/test.yml
This is required if the container is a bit older.
=> workflow: Run apt-get update before using apt

src/email.js
We want to _skip_ if the email does *not* match.
We'll definitely look into setting up an e2etest with a local IMAP server to be able to self-test this!
=> email: Fix logic of matching To header (TOC-5845)

src/browser_utils.js
Looks like they moved the settings arround behind a `.settings` property on the `Common` object. WIth the fix in place the network "preserve log" option works as expected again.
=> Fix unable to set "preserve log" on Puppeteer 14

src/config.js, tests/selftest_concurrency.js
By accident, we ignored `-S`/`--sequential` completely, and miscalculated in watch mode on machines with 1 or 2 CPU cores.
Add a bunch of tests, add support for `-`, and then default in watch mode only if neither `-S` nor `-C` is given.
=> Fix concurrency calculation

src/config.js, tests/selftest_config_setConfig.js
Allow human specifications like `--set-config server.url=https://example.com/`, and only make JSON optional.
Add a test to cover all of this.
=> Expand & test --set-config

tests/selftest_fetch.js
node's built-in error message changed from
> 'The operation was aborted.'
to
> 'This operation was aborted'
We don't care, match both.
=> Make selftest_fetch work on new node versions

src/email.js, tests/selftest_email.js, tests/selftest_getMail.js
Users can frequently receive emails at `joe.smith+test123@mail.com`. For some mailservices, this is a separate email address.
For others, it gets redirected to `joe.smith@mail.com`.
Support this with a new magic value; we need to due to the greenmail update.
=> email: Add new magic value __to_account__

.github/workflows/test.yml, package-lock.json, package.json
sharp has an implicit binary dependency on sharp-libvips, which it tries to download or build from source. Both fail with node 20.13.1 on ARM-based Macs. The download is valid, but somehow doesn't match the platform. The npm-install output contains this:
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-darwin-arm64v8.tar.br npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
Updating to a newer version of sharp fixes this issue.
=> update sharp dependency

src/assert_utils.js, tests/selftest_assertEventually.js
This way, a caller can construct the message function on failure, e.g. to provide information about the current status.
=> assertEventually: Add dynamic message function generation
